# Index <a name="indice"></a>

[Importación de librerías](#importacion_librerias)

[Funciones](#funciones)

[Importación de dato](#importacion_datos)

[Preprocesamiento](#preprocesamiento)


# 1.- Importación de librerías <a name="importacion_librerias"></a>

[Volver al índice](#indice)

In [82]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
import pickle

In [83]:
from sklearn.model_selection import train_test_split
from sklearn import tree

# 2.- Funciones <a name="funciones"></a>

[Volver al índice](#indice)

In [84]:
from javi_func import *

In [85]:
StrNow=GetStrNow()
StrNow

'20240422_1408'

In [86]:
OutputFolder='ExploratoryPreprocessing'

In [87]:
if not os.path.exists('../output/'+OutputFolder):
    os.makedirs('../output/'+OutputFolder)

In [88]:
os.mkdir('../output/'+OutputFolder+'/'+StrNow)

# 3.- Importación de datos <a name="importacion_datos"></a>

[Volver al índice](#indice)

In [89]:
#df=pd.read_pickle(r"TablaPlana.pkl", compression="bz2")

In [90]:
df=pd.read_csv('../input/df2_sample_R20000.csv', encoding='utf-8')

In [91]:
df.shape

(20000, 174)

In [92]:
df.head()

,Unnamed: 0,case_id,date_decision,MONTH,WEEK_NUM,target,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,...,sellerplacescnt_216L,sumoutstandtotal_3546847A,sumoutstandtotalest_4493215A,totaldebt_9A,totalsettled_863A,totinstallast1m_4525188A,twobodfilling_608L,typesuite_864L,validfrom_1069D,_merge
0,1301612,1895641,2020-08-19,202008,85,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,920606,1514635,2019-08-31,201908,34,0,0.0,6795.60,2477.600,0.0000,...,0.0,0.0,0.0,0.0,14531.601,NaN,FO,NaN,NaN,both
2,575184,959717,2020-02-18,202002,59,0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,943059,1537088,2019-09-14,201909,36,1,0.0,214471.80,3192.200,0.0000,...,0.0,0.0,0.0,0.0,323300.000,NaN,FO,NaN,NaN,both
4,1414680,2591435,2019-07-02,201907,26,0,0.0,201225.62,11481.601,5748.8003,...,1.0,34188.6,NaN,34188.6,383542.400,NaN,FO,NaN,2019-06-18,both

In [93]:
del df['Unnamed: 0']

In [94]:
df.head()

,case_id,date_decision,MONTH,WEEK_NUM,target,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,applicationcnt_361L,...,sellerplacescnt_216L,sumoutstandtotal_3546847A,sumoutstandtotalest_4493215A,totaldebt_9A,totalsettled_863A,totinstallast1m_4525188A,twobodfilling_608L,typesuite_864L,validfrom_1069D,_merge
0,1895641,2020-08-19,202008,85,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,1514635,2019-08-31,201908,34,0,0.0,6795.60,2477.600,0.0000,0.0,...,0.0,0.0,0.0,0.0,14531.601,NaN,FO,NaN,NaN,both
2,959717,2020-02-18,202002,59,0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,1537088,2019-09-14,201909,36,1,0.0,214471.80,3192.200,0.0000,0.0,...,0.0,0.0,0.0,0.0,323300.000,NaN,FO,NaN,NaN,both
4,2591435,2019-07-02,201907,26,0,0.0,201225.62,11481.601,5748.8003,0.0,...,1.0,34188.6,NaN,34188.6,383542.400,NaN,FO,NaN,2019-06-18,both

## 3.1 Variable Objetivo

In [95]:
VariableObjetivo='target'
print(df[VariableObjetivo].value_counts())
print(df[VariableObjetivo].value_counts(1))

0    18102
1     1898
Name: target, dtype: int64
0    0.9051
1    0.0949
Name: target, dtype: float64

# 5.- Preprocesamiento <a name="preprocesamiento"></a>

[Volver al índice](#indice)

## 5.1.- Subconjunto de datos sin nulos

In [96]:
df_NoNullsRows=df.copy()

In [97]:
df_NoNullsRows['DatosOK']=True

In [98]:
df_NoNullsRows['DatosOK'].value_counts()

True    20000
Name: DatosOK, dtype: int64

In [99]:
for Columna in df_NoNullsRows.columns:
    print('-'*20)
    print("Campo = "+Columna)
    print('')
    df_NoNullsRows.loc[df_NoNullsRows[Columna]!=df_NoNullsRows[Columna],'DatosOK']=False
    print(df_NoNullsRows['DatosOK'].value_counts(1))

--------------------
Campo = case_id

True    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = date_decision

True    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = MONTH

True    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = WEEK_NUM

True    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = target

True    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = actualdpdtolerance_344P

False    0.53355
True     0.46645
Name: DatosOK, dtype: float64
--------------------
Campo = amtinstpaidbefduel24m_4187115A

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = annuity_780A

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = annuitynextmonth_57A

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = applicationcnt_361L

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = applications30d_658L

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = applicationscnt_1086L

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = applicationscnt_464L

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = applicationscnt_629L

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = applicationscnt_867L

False    0.6189
True     0.3811
Name: DatosOK, dtype: float64
--------------------
Campo = avgdbddpdlast24m_3658932P

False    0.67695
True     0.32305
Name: DatosOK, dtype: float64
--------------------
Campo = avgdbddpdlast3m_4187120P

False    0.7677
True     0.2323
Name: DatosOK, dtype: float64
--------------------
Campo = avgdbdtollast24m_4525197P

False    0.89865
True     0.10135
Name: DatosOK, dtype: float64
--------------------
Campo = avgdpdtolclosure24_3658938P

False    0.89865
True     0.10135
Name: DatosOK, dtype: float64
--------------------
Campo = avginstallast24m_3658937A

False    0.8996
True     0.1004
Name: DatosOK, dtype: float64
--------------------
Campo = avglnamtstart24m_4525187A

False    0.9561
True     0.0439
Name: DatosOK, dtype: float64
--------------------
Campo = avgmaxdpdlast9m_3716943P

False    0.9561
True     0.0439
Name: DatosOK, dtype: float64
--------------------
Campo = avgoutstandbalancel6m_4187114A

False    0.95615
True     0.04385
Name: DatosOK, dtype: float64
--------------------
Campo = avgpmtlast12m_4525200A

False    0.95615
True     0.04385
Name: DatosOK, dtype: float64
--------------------
Campo = bankacctype_710L

False    0.99225
True     0.00775
Name: DatosOK, dtype: float64
--------------------
Campo = cardtype_51L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt12m_3712952L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt3m_3712950L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt6m_3712949L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_100L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_1022L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_1071L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_1130L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_136L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_157L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_257L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_304L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_360L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_493L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_533L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_887L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = clientscnt_946L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = cntincpaycont9m_3716944L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = cntpmts24_3658933L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = commnoinclast6m_3546845L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = credamount_770A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = credtype_322L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = currdebt_22A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = currdebtcredtyperange_828A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = datefirstoffer_1144D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = datelastinstal40dpd_247D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = datelastunpaid_3546854D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = daysoverduetolerancedd_3976961L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = deferredmnthsnum_166L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = disbursedcredamount_1113A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = disbursementtype_67L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = downpmt_116A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = dtlastpmtallstes_4499206D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = eir_270L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = equalitydataagreement_891L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = equalityempfrom_62L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = firstclxcampaign_1125D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = firstdatedue_489D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = homephncnt_628L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = inittransactionamount_650A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = inittransactioncode_186L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = interestrate_311L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = interestrategrace_34L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = isbidproduct_1095L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = isbidproductrequest_292L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = isdebitcard_729L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastactivateddate_801D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastapplicationdate_877D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastapprcommoditycat_1041M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastapprcommoditytypec_5251766M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastapprcredamount_781A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastapprdate_640D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastcancelreason_561M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastdelinqdate_224D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastdependentsnum_448L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastotherinc_902A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastotherlnsexpense_631A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrejectcommoditycat_161M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrejectcommodtypec_5251769M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrejectcredamount_222A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrejectdate_50D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrejectreason_759M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrejectreasonclient_4145040M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastrepayingdate_696D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = lastst_736L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maininc_215A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = mastercontrelectronic_519L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = mastercontrexist_109L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxannuity_159A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxannuity_4075009A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdbddpdlast1m_3658939P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdbddpdtollast12m_3658940P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdbddpdtollast6m_4187119P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdebt4_972A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdfrom6mto36m_3546853P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdinstldate_3546855D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdinstlnum_3546846P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdlast12m_727P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdlast24m_143P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdlast3m_392P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdlast6m_474P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdlast9m_1059P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxdpdtolerance_374P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxinstallast24m_3658928A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxlnamtstart6m_4525199A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxoutstandbalancel12m_4187113A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = maxpmtlast3m_4525190A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = mindbddpdlast24m_3658935P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = mindbdtollast24m_4525191P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = mobilephncnt_593L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = monthsannuity_845L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numactivecreds_622L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numactivecredschannel_414L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numactiverelcontr_750L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numcontrs3months_479L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numincomingpmts_3546848L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstlallpaidearly3d_817L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstls_657L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstlsallpaid_934L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstlswithdpd10_728L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstlswithdpd5_4187116L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstlswithoutdpd_562L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstmatpaidtearly2d_4499204L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaid_4499208L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearly3d_3546850L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearly3dest_4493216L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearly5d_1087L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearly5dest_4493211L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearly5dobd_4499205L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearly_338L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidearlyest_4493214L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidlastcontr_4325080L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstpaidlate1d_3546852L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstregularpaid_973L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstregularpaidest_4493210L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinsttopaygr_769L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinsttopaygrest_4493213L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstunpaidmax_3546851L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numinstunpaidmaxest_4493212L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numnotactivated_1143L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numpmtchanneldd_318L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = numrejects9m_859L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = opencred_647L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = paytype1st_925L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = paytype_783L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = payvacationpostpone_4187118D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = pctinstlsallpaidearl3d_427L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = pctinstlsallpaidlat10d_839L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = pctinstlsallpaidlate1d_3546856L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = pctinstlsallpaidlate4d_3546849L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = pctinstlsallpaidlate6d_3546844L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = pmtnum_254L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = posfpd10lastmonth_333P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = posfpd30lastmonth_3976960P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = posfstqpd30lastmonth_3976962P

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = previouscontdistrict_112M

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = price_1097A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = sellerplacecnt_915L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = sellerplacescnt_216L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = sumoutstandtotal_3546847A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = sumoutstandtotalest_4493215A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = totaldebt_9A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = totalsettled_863A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = totinstallast1m_4525188A

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = twobodfilling_608L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = typesuite_864L

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = validfrom_1069D

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = _merge

False    1.0
Name: DatosOK, dtype: float64
--------------------
Campo = DatosOK

False    1.0
Name: DatosOK, dtype: float64

In [100]:
df_NoNullsRows['DatosOK'].value_counts()

False    20000
Name: DatosOK, dtype: int64

## 5.5- Preparación de tabla minable

### 5.5.1- Tratamiento de nulos

In [101]:
df.shape

(20000, 173)

In [102]:
df10=FindNulls(df)
df10.shape

(20000, 340)

In [103]:
df11, df_imputation_values=Imputer(df10)
print(df11.shape)
print(df_imputation_values.shape)

(20000, 930)
(340, 6)

In [104]:
df11

,case_id,date_decision,MONTH,WEEK_NUM,target,actualdpdtolerance_344P,amtinstpaidbefduel24m_4187115A,annuity_780A,annuitynextmonth_57A,applicationcnt_361L,...,lastst_736L_NullValImp,maxdpdinstldate_3546855D_NullValImp,opencred_647L_NullValImp,paytype1st_925L_NullValImp,paytype_783L_NullValImp,payvacationpostpone_4187118D_NullValImp,previouscontdistrict_112M_NullValImp,twobodfilling_608L_NullValImp,typesuite_864L_NullValImp,validfrom_1069D_NullValImp
0,1895641,2020-08-19,202008,85,0,NaN,NaN,NaN,NaN,NaN,...,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue
1,1514635,2019-08-31,201908,34,0,0.0,6795.60,2477.600,0.0000,0.0,...,K,2018-03-22,False,OTHER,OTHER,NullValue,P196_6_173,FO,NullValue,NullValue
2,959717,2020-02-18,202002,59,0,NaN,NaN,NaN,NaN,NaN,...,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue
3,1537088,2019-09-14,201909,36,1,0.0,214471.80,3192.200,0.0000,0.0,...,D,2019-03-24,False,OTHER,OTHER,NullValue,P131_33_167,FO,NullValue,NullValue
4,2591435,2019-07-02,201907,26,0,0.0,201225.62,11481.601,5748.8003,0.0,...,A,2019-03-31,False,OTHER,OTHER,NullValue,P147_21_170,FO,NullValue,2019-06-18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,1860842,2020-06-12,202006,75,0,NaN,NaN,NaN,NaN,NaN,...,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue
19996,1805191,2020-03-04,202003,61,0,NaN,NaN,NaN,NaN,NaN,...,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue
19997,670323,2019-04-12,201904,14,0,NaN,NaN,2158.200,0.0000,0.0,...,NullValue,NullValue,NullValue,OTHER,OTHER,NullValue,a55475b1,FO,AL,NullValue
19998,662220,2019-03-31,201903,12,0,0.0,0.00,3160.800,3358.4001,0.0,...,A,2019-03-29,False,OTHER,OTHER,NullValue,P91_101_191,FO,AL,NullValue
19999,1740162,2020-01-08,202001,53,0,NaN,NaN,NaN,NaN,NaN,...,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue,NullValue

In [105]:
df_imputation_values.sample(50)

,MinImp,MaxImp,MeanImp,MedianImp,MostFreqImp,NullValImp
Field,,,,,,
currdebtcredtyperange_828A,0.0,560547.1,10247.711444,0.00000,NaN,NaN
interestrategrace_34L,0.0,0.0,0.000000,0.00000,NaN,NaN
maxdpdinstldate_3546855D_NN,NaN,NaN,NaN,NaN,NaN,NaN
mastercontrexist_109L,0.0,0.0,0.000000,0.00000,NaN,NaN
typesuite_864L_NN,NaN,NaN,NaN,NaN,NaN,NaN
totaldebt_9A,0.0,1092393.0,18309.377003,0.00000,NaN,NaN
avginstallast24m_3658937A_NN,NaN,NaN,NaN,NaN,NaN,NaN
previouscontdistrict_112M_NN,NaN,NaN,NaN,NaN,NaN,NaN
numinstpaidlastcontr_4325080L_NN,NaN,NaN,NaN,NaN,NaN,NaN
clientscnt_887L,0.0,1154.0,3.291110,0.00000,NaN,NaN
lastst_736L,NaN,NaN,NaN,NaN,D,NullValue
lastactivateddate_801D,NaN,NaN,NaN,NaN,2019-01-31,NullValue
validfrom_1069D,NaN,NaN,NaN,NaN,2019-06-18,NullValue
numactivecreds_622L_NN,NaN,NaN,NaN,NaN,NaN,NaN
posfpd30lastmonth_3976960P_NN,NaN,NaN,NaN,NaN,NaN,NaN
maxannuity_159A_NN,NaN,NaN,NaN,NaN,NaN,NaN
clientscnt_1071L_NN,NaN,NaN,NaN,NaN,NaN,NaN
pctinstlsallpaidearl3d_427L,0.0,6.0,0.592980,0.61111,NaN,NaN
pctinstlsallpaidlate6d_3546844L,0.0,1.0,0.104326,0.00000,NaN,NaN
validfrom_1069D_NN,NaN,NaN,NaN,NaN,NaN,NaN
lastapprdate_640D,NaN,NaN,NaN,NaN,2018-12-07,NullValue
numinstlswithoutdpd_562L,0.0,263.0,28.973479,19.00000,NaN,NaN
clientscnt_100L,0.0,3.0,0.051288,0.00000,NaN,NaN
datelastunpaid_3546854D_NN,NaN,NaN,NaN,NaN,NaN,NaN
lastrejectdate_50D_NN,NaN,NaN,NaN,NaN,NaN,NaN
numinstpaidearly5dest_4493211L,0.0,37.0,3.157531,2.00000,NaN,NaN
annuitynextmonth_57A_NN,NaN,NaN,NaN,NaN,NaN,NaN
avgdbdtollast24m_4525197P,-853.0,4378.0,39.383438,-5.00000,NaN,NaN
case_id,NaN,NaN,NaN,NaN,NaN,NaN
clientscnt_157L_NN,NaN,NaN,NaN,NaN,NaN,NaN
mobilephncnt_593L_NN,NaN,NaN,NaN,NaN,NaN,NaN
cntpmts24_3658933L,0.0,25.0,10.190065,9.00000,NaN,NaN
paytype1st_925L_NN,NaN,NaN,NaN,NaN,NaN,NaN
lastapprcommoditytypec_5251766M_NN,NaN,NaN,NaN,NaN,NaN,NaN
mastercontrexist_109L_NN,NaN,NaN,NaN,NaN,NaN,NaN
numinsttopaygrest_4493213L_NN,NaN,NaN,NaN,NaN,NaN,NaN
deferredmnthsnum_166L_NN,NaN,NaN,NaN,NaN,NaN,NaN
avgdbddpdlast24m_3658932P_NN,NaN,NaN,NaN,NaN,NaN,NaN
applicationcnt_361L_NN,NaN,NaN,NaN,NaN,NaN,NaN
maxdbddpdlast1m_3658939P,-313.0,4432.0,49.819996,-2.00000,NaN,NaN
bankacctype_710L,NaN,NaN,NaN,NaN,CA,NullValue
currdebt_22A_NN,NaN,NaN,NaN,NaN,NaN,NaN
lastrejectreasonclient_4145040M,NaN,NaN,NaN,NaN,a55475b1,NullValue
numinstunpaidmaxest_4493212L_NN,NaN,NaN,NaN,NaN,NaN,NaN
homephncnt_628L,0.0,7.0,0.615983,0.00000,NaN,NaN
numinstpaidlate1d_3546852L,0.0,88.0,5.256629,2.00000,NaN,NaN
eir_270L_NN,NaN,NaN,NaN,NaN,NaN,NaN
applicationscnt_464L_NN,NaN,NaN,NaN,NaN,NaN,NaN
clientscnt_257L,0.0,2.0,0.003626,0.00000,NaN,NaN
numcontrs3months_479L,0.0,23.0,0.270338,0.00000,NaN,NaN

In [106]:
df_imputation_values.to_csv('../output/'+OutputFolder+'/'+StrNow+'/df_imputation_values.csv')

In [107]:
df_fields_imputed=DescribeDf(df11)
df_fields_imputed.sample(20)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max,type,nunique,nulls,nulls_ratio
maxdbddpdtollast6m_4187119P_MedianImp,20000,NaN,NaN,NaN,14.4025,236.263,-226,0,0,0,4432,float64,235,0,0.00000
interestrategrace_34L,244,NaN,NaN,NaN,0,0,0,0,0,0,0,float64,1,19756,0.98780
clientscnt6m_3712949L_MedianImp,20000,NaN,NaN,NaN,0.0165,0.273188,0,0,0,0,31,float64,7,0,0.00000
numinstpaidlastcontr_4325080L_MeanImp,20000,NaN,NaN,NaN,7.66943,3.28252,0,7.66943,7.66943,7.66943,58,float64,47,0,0.00000
equalityempfrom_62L_MostFreqImp,20000,2,True,19986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,bool,2,0,0.00000
maxdpdfrom6mto36m_3546853P_MeanImp,20000,NaN,NaN,NaN,31.2682,163.296,0,0,31.2682,31.2682,4266,float64,355,0,0.00000
avglnamtstart24m_4525187A_MedianImp,20000,NaN,NaN,NaN,28033,10815.9,2092,27221,27221,27221,403980,float64,780,0,0.00000
maxinstallast24m_3658928A_MeanImp,20000,NaN,NaN,NaN,13216.7,13663.4,6.4,9422.4,13216.7,13216.7,307492,float64,7121,0,0.00000
daysoverduetolerancedd_3976961L_MeanImp,20000,NaN,NaN,NaN,97.158,324.942,0,3,97.158,97.158,4925,float64,641,0,0.00000
applicationscnt_1086L_MinImp,20000,NaN,NaN,NaN,0.2851,2.75987,0,0,0,0,258,float64,46,0,0.00000
numcontrs3months_479L_MaxImp,20000,NaN,NaN,NaN,7.9541,10.771,0,0,0,23,23,float64,18,0,0.00000
equalitydataagreement_891L_NullValImp,20000,3,NullValue,19311,NaN,NaN,NaN,NaN,NaN,NaN,NaN,object,3,0,0.00000
currdebtcredtyperange_828A_MinImp,20000,NaN,NaN,NaN,6783.47,27716.6,0,0,0,0,560547,float64,2662,0,0.00000
numinstls_657L_MeanImp,20000,NaN,NaN,NaN,7.32011,11.7072,0,0,7.32011,7.32011,197,float64,99,0,0.00000
clientscnt12m_3712952L_NN,20000,NaN,NaN,NaN,0.66195,0.473057,0,0,1,1,1,int32,2,0,0.00000
datefirstoffer_1144D_MostFreqImp,20000,629,2008-04-03,15405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,object,629,0,0.00000
sumoutstandtotalest_4493215A_MinImp,20000,NaN,NaN,NaN,5103.5,27000.8,0,0,0,0,923352,float64,1800,0,0.00000
dtlastpmtallstes_4499206D_MostFreqImp,20000,1049,2019-09-16,16848,NaN,NaN,NaN,NaN,NaN,NaN,NaN,object,1049,0,0.00000
totinstallast1m_4525188A,1845,NaN,NaN,NaN,10420,16313.9,38.54,3220.8,6079.8,11292.5,316645,float64,1821,18155,0.90775
totinstallast1m_4525188A_NN,20000,NaN,NaN,NaN,0.09225,0.289386,0,0,0,0,1,int32,2,0,0.00000

### 5.5.1.- Numéricas

In [108]:
MaskNumNotNull=(((df_fields_imputed.type=='float64') | (df_fields_imputed.type=='int64')) & (df_fields_imputed.nulls==0))

In [109]:
MaskNumNotNull.mean()

0.5548387096774193

In [110]:
VariablesNumericas=df_fields_imputed[MaskNumNotNull].index.values
VariablesNumericas

array(['case_id', 'MONTH', 'WEEK_NUM', 'target',
       'actualdpdtolerance_344P_MinImp',
       'amtinstpaidbefduel24m_4187115A_MinImp', 'annuity_780A_MinImp',
       'annuitynextmonth_57A_MinImp', 'applicationcnt_361L_MinImp',
       'applications30d_658L_MinImp', 'applicationscnt_1086L_MinImp',
       'applicationscnt_464L_MinImp', 'applicationscnt_629L_MinImp',
       'applicationscnt_867L_MinImp', 'avgdbddpdlast24m_3658932P_MinImp',
       'avgdbddpdlast3m_4187120P_MinImp',
       'avgdbdtollast24m_4525197P_MinImp',
       'avgdpdtolclosure24_3658938P_MinImp',
       'avginstallast24m_3658937A_MinImp',
       'avglnamtstart24m_4525187A_MinImp',
       'avgmaxdpdlast9m_3716943P_MinImp',
       'avgoutstandbalancel6m_4187114A_MinImp',
       'avgpmtlast12m_4525200A_MinImp', 'clientscnt12m_3712952L_MinImp',
       'clientscnt3m_3712950L_MinImp', 'clientscnt6m_3712949L_MinImp',
       'clientscnt_100L_MinImp', 'clientscnt_1022L_MinImp',
       'clientscnt_1071L_MinImp', 'clientscnt_1130L_MinImp',
       'clientscnt_136L_MinImp', 'clientscnt_157L_MinImp',
       'clientscnt_257L_MinImp', 'clientscnt_304L_MinImp',
       'clientscnt_360L_MinImp', 'clientscnt_493L_MinImp',
       'clientscnt_533L_MinImp', 'clientscnt_887L_MinImp',
       'clientscnt_946L_MinImp', 'cntincpaycont9m_3716944L_MinImp',
       'cntpmts24_3658933L_MinImp', 'commnoinclast6m_3546845L_MinImp',
       'credamount_770A_MinImp', 'currdebt_22A_MinImp',
       'currdebtcredtyperange_828A_MinImp',
       'daysoverduetolerancedd_3976961L_MinImp',
       'deferredmnthsnum_166L_MinImp', 'disbursedcredamount_1113A_MinImp',
       'downpmt_116A_MinImp', 'eir_270L_MinImp', 'homephncnt_628L_MinImp',
       'inittransactionamount_650A_MinImp', 'interestrate_311L_MinImp',
       'interestrategrace_34L_MinImp', 'lastapprcredamount_781A_MinImp',
       'lastdependentsnum_448L_MinImp', 'lastotherinc_902A_MinImp',
       'lastotherlnsexpense_631A_MinImp',
       'lastrejectcredamount_222A_MinImp', 'maininc_215A_MinImp',
       'mastercontrelectronic_519L_MinImp',
       'mastercontrexist_109L_MinImp', 'maxannuity_159A_MinImp',
       'maxannuity_4075009A_MinImp', 'maxdbddpdlast1m_3658939P_MinImp',
       'maxdbddpdtollast12m_3658940P_MinImp',
       'maxdbddpdtollast6m_4187119P_MinImp', 'maxdebt4_972A_MinImp',
       'maxdpdfrom6mto36m_3546853P_MinImp',
       'maxdpdinstlnum_3546846P_MinImp', 'maxdpdlast12m_727P_MinImp',
       'maxdpdlast24m_143P_MinImp', 'maxdpdlast3m_392P_MinImp',
       'maxdpdlast6m_474P_MinImp', 'maxdpdlast9m_1059P_MinImp',
       'maxdpdtolerance_374P_MinImp', 'maxinstallast24m_3658928A_MinImp',
       'maxlnamtstart6m_4525199A_MinImp',
       'maxoutstandbalancel12m_4187113A_MinImp',
       'maxpmtlast3m_4525190A_MinImp', 'mindbddpdlast24m_3658935P_MinImp',
       'mindbdtollast24m_4525191P_MinImp', 'mobilephncnt_593L_MinImp',
       'monthsannuity_845L_MinImp', 'numactivecreds_622L_MinImp',
       'numactivecredschannel_414L_MinImp',
       'numactiverelcontr_750L_MinImp', 'numcontrs3months_479L_MinImp',
       'numincomingpmts_3546848L_MinImp',
       'numinstlallpaidearly3d_817L_MinImp', 'numinstls_657L_MinImp',
       'numinstlsallpaid_934L_MinImp', 'numinstlswithdpd10_728L_MinImp',
       'numinstlswithdpd5_4187116L_MinImp',
       'numinstlswithoutdpd_562L_MinImp',
       'numinstmatpaidtearly2d_4499204L_MinImp',
       'numinstpaid_4499208L_MinImp',
       'numinstpaidearly3d_3546850L_MinImp',
       'numinstpaidearly3dest_4493216L_MinImp',
       'numinstpaidearly5d_1087L_MinImp',
       'numinstpaidearly5dest_4493211L_MinImp',
       'numinstpaidearly5dobd_4499205L_MinImp',
       'numinstpaidearly_338L_MinImp',
       'numinstpaidearlyest_4493214L_MinImp',
       'numinstpaidlastcontr_4325080L_MinImp',
       'numinstpaidlate1d_3546852L_MinImp',
       'numinstregularpaid_973L_MinImp',
       'numinstregularpaidest_4493210L_MinImp',
       'numinsttopaygr_769L_MinImp', 'numinsttopaygrest_4493213L_MinImp',
       'numinstunpaidmax_3546851L_MinImp',
       'numinstunpaidmaxest_4493212L_MinImp',
       'numnotactivated_1143L_MinImp', 'numpmtchanneldd_318L_MinImp',
       'numrejects9m_859L_MinImp', 'pctinstlsallpaidearl3d_427L_MinImp',
       'pctinstlsallpaidlat10d_839L_MinImp',
       'pctinstlsallpaidlate1d_3546856L_MinImp',
       'pctinstlsallpaidlate4d_3546849L_MinImp',
       'pctinstlsallpaidlate6d_3546844L_MinImp', 'pmtnum_254L_MinImp',
       'posfpd10lastmonth_333P_MinImp',
       'posfpd30lastmonth_3976960P_MinImp',
       'posfstqpd30lastmonth_3976962P_MinImp', 'price_1097A_MinImp',
       'sellerplacecnt_915L_MinImp', 'sellerplacescnt_216L_MinImp',
       'sumoutstandtotal_3546847A_MinImp',
       'sumoutstandtotalest_4493215A_MinImp', 'totaldebt_9A_MinImp',
       'totalsettled_863A_MinImp', 'totinstallast1m_4525188A_MinImp',
       'actualdpdtolerance_344P_MaxImp',
       'amtinstpaidbefduel24m_4187115A_MaxImp', 'annuity_780A_MaxImp',
       'annuitynextmonth_57A_MaxImp', 'applicationcnt_361L_MaxImp',
       'applications30d_658L_MaxImp', 'applicationscnt_1086L_MaxImp',
       'applicationscnt_464L_MaxImp', 'applicationscnt_629L_MaxImp',
       'applicationscnt_867L_MaxImp', 'avgdbddpdlast24m_3658932P_MaxImp',
       'avgdbddpdlast3m_4187120P_MaxImp',
       'avgdbdtollast24m_4525197P_MaxImp',
       'avgdpdtolclosure24_3658938P_MaxImp',
       'avginstallast24m_3658937A_MaxImp',
       'avglnamtstart24m_4525187A_MaxImp',
       'avgmaxdpdlast9m_3716943P_MaxImp',
       'avgoutstandbalancel6m_4187114A_MaxImp',
       'avgpmtlast12m_4525200A_MaxImp', 'clientscnt12m_3712952L_MaxImp',
       'clientscnt3m_3712950L_MaxImp', 'clientscnt6m_3712949L_MaxImp',
       'clientscnt_100L_MaxImp', 'clientscnt_1022L_MaxImp',
       'clientscnt_1071L_MaxImp', 'clientscnt_1130L_MaxImp',
       'clientscnt_136L_MaxImp', 'clientscnt_157L_MaxImp',
       'clientscnt_257L_MaxImp', 'clientscnt_304L_MaxImp',
       'clientscnt_360L_MaxImp', 'clientscnt_493L_MaxImp',
       'clientscnt_533L_MaxImp', 'clientscnt_887L_MaxImp',
       'clientscnt_946L_MaxImp', 'cntincpaycont9m_3716944L_MaxImp',
       'cntpmts24_3658933L_MaxImp', 'commnoinclast6m_3546845L_MaxImp',
       'credamount_770A_MaxImp', 'currdebt_22A_MaxImp',
       'currdebtcredtyperange_828A_MaxImp',
       'daysoverduetolerancedd_3976961L_MaxImp',
       'deferredmnthsnum_166L_MaxImp', 'disbursedcredamount_1113A_MaxImp',
       'downpmt_116A_MaxImp', 'eir_270L_MaxImp', 'homephncnt_628L_MaxImp',
       'inittransactionamount_650A_MaxImp', 'interestrate_311L_MaxImp',
       'interestrategrace_34L_MaxImp', 'lastapprcredamount_781A_MaxImp',
       'lastdependentsnum_448L_MaxImp', 'lastotherinc_902A_MaxImp',
       'lastotherlnsexpense_631A_MaxImp',
       'lastrejectcredamount_222A_MaxImp', 'maininc_215A_MaxImp',
       'mastercontrelectronic_519L_MaxImp',
       'mastercontrexist_109L_MaxImp', 'maxannuity_159A_MaxImp',
       'maxannuity_4075009A_MaxImp', 'maxdbddpdlast1m_3658939P_MaxImp',
       'maxdbddpdtollast12m_3658940P_MaxImp',
       'maxdbddpdtollast6m_4187119P_MaxImp', 'maxdebt4_972A_MaxImp',
       'maxdpdfrom6mto36m_3546853P_MaxImp',
       'maxdpdinstlnum_3546846P_MaxImp', 'maxdpdlast12m_727P_MaxImp',
       'maxdpdlast24m_143P_MaxImp', 'maxdpdlast3m_392P_MaxImp',
       'maxdpdlast6m_474P_MaxImp', 'maxdpdlast9m_1059P_MaxImp',
       'maxdpdtolerance_374P_MaxImp', 'maxinstallast24m_3658928A_MaxImp',
       'maxlnamtstart6m_4525199A_MaxImp',
       'maxoutstandbalancel12m_4187113A_MaxImp',
       'maxpmtlast3m_4525190A_MaxImp', 'mindbddpdlast24m_3658935P_MaxImp',
       'mindbdtollast24m_4525191P_MaxImp', 'mobilephncnt_593L_MaxImp',
       'monthsannuity_845L_MaxImp', 'numactivecreds_622L_MaxImp',
       'numactivecredschannel_414L_MaxImp',
       'numactiverelcontr_750L_MaxImp', 'numcontrs3months_479L_MaxImp',
       'numincomingpmts_3546848L_MaxImp',
       'numinstlallpaidearly3d_817L_MaxImp', 'numinstls_657L_MaxImp',
       'numinstlsallpaid_934L_MaxImp', 'numinstlswithdpd10_728L_MaxImp',
       'numinstlswithdpd5_4187116L_MaxImp',
       'numinstlswithoutdpd_562L_MaxImp',
       'numinstmatpaidtearly2d_4499204L_MaxImp',
       'numinstpaid_4499208L_MaxImp',
       'numinstpaidearly3d_3546850L_MaxImp',
       'numinstpaidearly3dest_4493216L_MaxImp',
       'numinstpaidearly5d_1087L_MaxImp',
       'numinstpaidearly5dest_4493211L_MaxImp',
       'numinstpaidearly5dobd_4499205L_MaxImp',
       'numinstpaidearly_338L_MaxImp',
       'numinstpaidearlyest_4493214L_MaxImp',
       'numinstpaidlastcontr_4325080L_MaxImp',
       'numinstpaidlate1d_3546852L_MaxImp',
       'numinstregularpaid_973L_MaxImp',
       'numinstregularpaidest_4493210L_MaxImp',
       'numinsttopaygr_769L_MaxImp', 'numinsttopaygrest_4493213L_MaxImp',
       'numinstunpaidmax_3546851L_MaxImp',
       'numinstunpaidmaxest_4493212L_MaxImp',
       'numnotactivated_1143L_MaxImp', 'numpmtchanneldd_318L_MaxImp',
       'numrejects9m_859L_MaxImp', 'pctinstlsallpaidearl3d_427L_MaxImp',
       'pctinstlsallpaidlat10d_839L_MaxImp',
       'pctinstlsallpaidlate1d_3546856L_MaxImp',
       'pctinstlsallpaidlate4d_3546849L_MaxImp',
       'pctinstlsallpaidlate6d_3546844L_MaxImp', 'pmtnum_254L_MaxImp',
       'posfpd10lastmonth_333P_MaxImp',
       'posfpd30lastmonth_3976960P_MaxImp',
       'posfstqpd30lastmonth_3976962P_MaxImp', 'price_1097A_MaxImp',
       'sellerplacecnt_915L_MaxImp', 'sellerplacescnt_216L_MaxImp',
       'sumoutstandtotal_3546847A_MaxImp',
       'sumoutstandtotalest_4493215A_MaxImp', 'totaldebt_9A_MaxImp',
       'totalsettled_863A_MaxImp', 'totinstallast1m_4525188A_MaxImp',
       'actualdpdtolerance_344P_MeanImp',
       'amtinstpaidbefduel24m_4187115A_MeanImp', 'annuity_780A_MeanImp',
       'annuitynextmonth_57A_MeanImp', 'applicationcnt_361L_MeanImp',
       'applications30d_658L_MeanImp', 'applicationscnt_1086L_MeanImp',
       'applicationscnt_464L_MeanImp', 'applicationscnt_629L_MeanImp',
       'applicationscnt_867L_MeanImp',
       'avgdbddpdlast24m_3658932P_MeanImp',
       'avgdbddpdlast3m_4187120P_MeanImp',
       'avgdbdtollast24m_4525197P_MeanImp',
       'avgdpdtolclosure24_3658938P_MeanImp',
       'avginstallast24m_3658937A_MeanImp',
       'avglnamtstart24m_4525187A_MeanImp',
       'avgmaxdpdlast9m_3716943P_MeanImp',
       'avgoutstandbalancel6m_4187114A_MeanImp',
       'avgpmtlast12m_4525200A_MeanImp', 'clientscnt12m_3712952L_MeanImp',
       'clientscnt3m_3712950L_MeanImp', 'clientscnt6m_3712949L_MeanImp',
       'clientscnt_100L_MeanImp', 'clientscnt_1022L_MeanImp',
       'clientscnt_1071L_MeanImp', 'clientscnt_1130L_MeanImp',
       'clientscnt_136L_MeanImp', 'clientscnt_157L_MeanImp',
       'clientscnt_257L_MeanImp', 'clientscnt_304L_MeanImp',
       'clientscnt_360L_MeanImp', 'clientscnt_493L_MeanImp',
       'clientscnt_533L_MeanImp', 'clientscnt_887L_MeanImp',
       'clientscnt_946L_MeanImp', 'cntincpaycont9m_3716944L_MeanImp',
       'cntpmts24_3658933L_MeanImp', 'commnoinclast6m_3546845L_MeanImp',
       'credamount_770A_MeanImp', 'currdebt_22A_MeanImp',
       'currdebtcredtyperange_828A_MeanImp',
       'daysoverduetolerancedd_3976961L_MeanImp',
       'deferredmnthsnum_166L_MeanImp',
       'disbursedcredamount_1113A_MeanImp', 'downpmt_116A_MeanImp',
       'eir_270L_MeanImp', 'homephncnt_628L_MeanImp',
       'inittransactionamount_650A_MeanImp', 'interestrate_311L_MeanImp',
       'interestrategrace_34L_MeanImp', 'lastapprcredamount_781A_MeanImp',
       'lastdependentsnum_448L_MeanImp', 'lastotherinc_902A_MeanImp',
       'lastotherlnsexpense_631A_MeanImp',
       'lastrejectcredamount_222A_MeanImp', 'maininc_215A_MeanImp',
       'mastercontrelectronic_519L_MeanImp',
       'mastercontrexist_109L_MeanImp', 'maxannuity_159A_MeanImp',
       'maxannuity_4075009A_MeanImp', 'maxdbddpdlast1m_3658939P_MeanImp',
       'maxdbddpdtollast12m_3658940P_MeanImp',
       'maxdbddpdtollast6m_4187119P_MeanImp', 'maxdebt4_972A_MeanImp',
       'maxdpdfrom6mto36m_3546853P_MeanImp',
       'maxdpdinstlnum_3546846P_MeanImp', 'maxdpdlast12m_727P_MeanImp',
       'maxdpdlast24m_143P_MeanImp', 'maxdpdlast3m_392P_MeanImp',
       'maxdpdlast6m_474P_MeanImp', 'maxdpdlast9m_1059P_MeanImp',
       'maxdpdtolerance_374P_MeanImp',
       'maxinstallast24m_3658928A_MeanImp',
       'maxlnamtstart6m_4525199A_MeanImp',
       'maxoutstandbalancel12m_4187113A_MeanImp',
       'maxpmtlast3m_4525190A_MeanImp',
       'mindbddpdlast24m_3658935P_MeanImp',
       'mindbdtollast24m_4525191P_MeanImp', 'mobilephncnt_593L_MeanImp',
       'monthsannuity_845L_MeanImp', 'numactivecreds_622L_MeanImp',
       'numactivecredschannel_414L_MeanImp',
       'numactiverelcontr_750L_MeanImp', 'numcontrs3months_479L_MeanImp',
       'numincomingpmts_3546848L_MeanImp',
       'numinstlallpaidearly3d_817L_MeanImp', 'numinstls_657L_MeanImp',
       'numinstlsallpaid_934L_MeanImp', 'numinstlswithdpd10_728L_MeanImp',
       'numinstlswithdpd5_4187116L_MeanImp',
       'numinstlswithoutdpd_562L_MeanImp',
       'numinstmatpaidtearly2d_4499204L_MeanImp',
       'numinstpaid_4499208L_MeanImp',
       'numinstpaidearly3d_3546850L_MeanImp',
       'numinstpaidearly3dest_4493216L_MeanImp',
       'numinstpaidearly5d_1087L_MeanImp',
       'numinstpaidearly5dest_4493211L_MeanImp',
       'numinstpaidearly5dobd_4499205L_MeanImp',
       'numinstpaidearly_338L_MeanImp',
       'numinstpaidearlyest_4493214L_MeanImp',
       'numinstpaidlastcontr_4325080L_MeanImp',
       'numinstpaidlate1d_3546852L_MeanImp',
       'numinstregularpaid_973L_MeanImp',
       'numinstregularpaidest_4493210L_MeanImp',
       'numinsttopaygr_769L_MeanImp',
       'numinsttopaygrest_4493213L_MeanImp',
       'numinstunpaidmax_3546851L_MeanImp',
       'numinstunpaidmaxest_4493212L_MeanImp',
       'numnotactivated_1143L_MeanImp', 'numpmtchanneldd_318L_MeanImp',
       'numrejects9m_859L_MeanImp', 'pctinstlsallpaidearl3d_427L_MeanImp',
       'pctinstlsallpaidlat10d_839L_MeanImp',
       'pctinstlsallpaidlate1d_3546856L_MeanImp',
       'pctinstlsallpaidlate4d_3546849L_MeanImp',
       'pctinstlsallpaidlate6d_3546844L_MeanImp', 'pmtnum_254L_MeanImp',
       'posfpd10lastmonth_333P_MeanImp',
       'posfpd30lastmonth_3976960P_MeanImp',
       'posfstqpd30lastmonth_3976962P_MeanImp', 'price_1097A_MeanImp',
       'sellerplacecnt_915L_MeanImp', 'sellerplacescnt_216L_MeanImp',
       'sumoutstandtotal_3546847A_MeanImp',
       'sumoutstandtotalest_4493215A_MeanImp', 'totaldebt_9A_MeanImp',
       'totalsettled_863A_MeanImp', 'totinstallast1m_4525188A_MeanImp',
       'actualdpdtolerance_344P_MedianImp',
       'amtinstpaidbefduel24m_4187115A_MedianImp',
       'annuity_780A_MedianImp', 'annuitynextmonth_57A_MedianImp',
       'applicationcnt_361L_MedianImp', 'applications30d_658L_MedianImp',
       'applicationscnt_1086L_MedianImp',
       'applicationscnt_464L_MedianImp', 'applicationscnt_629L_MedianImp',
       'applicationscnt_867L_MedianImp',
       'avgdbddpdlast24m_3658932P_MedianImp',
       'avgdbddpdlast3m_4187120P_MedianImp',
       'avgdbdtollast24m_4525197P_MedianImp',
       'avgdpdtolclosure24_3658938P_MedianImp',
       'avginstallast24m_3658937A_MedianImp',
       'avglnamtstart24m_4525187A_MedianImp',
       'avgmaxdpdlast9m_3716943P_MedianImp',
       'avgoutstandbalancel6m_4187114A_MedianImp',
       'avgpmtlast12m_4525200A_MedianImp',
       'clientscnt12m_3712952L_MedianImp',
       'clientscnt3m_3712950L_MedianImp',
       'clientscnt6m_3712949L_MedianImp', 'clientscnt_100L_MedianImp',
       'clientscnt_1022L_MedianImp', 'clientscnt_1071L_MedianImp',
       'clientscnt_1130L_MedianImp', 'clientscnt_136L_MedianImp',
       'clientscnt_157L_MedianImp', 'clientscnt_257L_MedianImp',
       'clientscnt_304L_MedianImp', 'clientscnt_360L_MedianImp',
       'clientscnt_493L_MedianImp', 'clientscnt_533L_MedianImp',
       'clientscnt_887L_MedianImp', 'clientscnt_946L_MedianImp',
       'cntincpaycont9m_3716944L_MedianImp',
       'cntpmts24_3658933L_MedianImp',
       'commnoinclast6m_3546845L_MedianImp', 'credamount_770A_MedianImp',
       'currdebt_22A_MedianImp', 'currdebtcredtyperange_828A_MedianImp',
       'daysoverduetolerancedd_3976961L_MedianImp',
       'deferredmnthsnum_166L_MedianImp',
       'disbursedcredamount_1113A_MedianImp', 'downpmt_116A_MedianImp',
       'eir_270L_MedianImp', 'homephncnt_628L_MedianImp',
       'inittransactionamount_650A_MedianImp',
       'interestrate_311L_MedianImp', 'interestrategrace_34L_MedianImp',
       'lastapprcredamount_781A_MedianImp',
       'lastdependentsnum_448L_MedianImp', 'lastotherinc_902A_MedianImp',
       'lastotherlnsexpense_631A_MedianImp',
       'lastrejectcredamount_222A_MedianImp', 'maininc_215A_MedianImp',
       'mastercontrelectronic_519L_MedianImp',
       'mastercontrexist_109L_MedianImp', 'maxannuity_159A_MedianImp',
       'maxannuity_4075009A_MedianImp',
       'maxdbddpdlast1m_3658939P_MedianImp',
       'maxdbddpdtollast12m_3658940P_MedianImp',
       'maxdbddpdtollast6m_4187119P_MedianImp', 'maxdebt4_972A_MedianImp',
       'maxdpdfrom6mto36m_3546853P_MedianImp',
       'maxdpdinstlnum_3546846P_MedianImp',
       'maxdpdlast12m_727P_MedianImp', 'maxdpdlast24m_143P_MedianImp',
       'maxdpdlast3m_392P_MedianImp', 'maxdpdlast6m_474P_MedianImp',
       'maxdpdlast9m_1059P_MedianImp', 'maxdpdtolerance_374P_MedianImp',
       'maxinstallast24m_3658928A_MedianImp',
       'maxlnamtstart6m_4525199A_MedianImp',
       'maxoutstandbalancel12m_4187113A_MedianImp',
       'maxpmtlast3m_4525190A_MedianImp',
       'mindbddpdlast24m_3658935P_MedianImp',
       'mindbdtollast24m_4525191P_MedianImp',
       'mobilephncnt_593L_MedianImp', 'monthsannuity_845L_MedianImp',
       'numactivecreds_622L_MedianImp',
       'numactivecredschannel_414L_MedianImp',
       'numactiverelcontr_750L_MedianImp',
       'numcontrs3months_479L_MedianImp',
       'numincomingpmts_3546848L_MedianImp',
       'numinstlallpaidearly3d_817L_MedianImp',
       'numinstls_657L_MedianImp', 'numinstlsallpaid_934L_MedianImp',
       'numinstlswithdpd10_728L_MedianImp',
       'numinstlswithdpd5_4187116L_MedianImp',
       'numinstlswithoutdpd_562L_MedianImp',
       'numinstmatpaidtearly2d_4499204L_MedianImp',
       'numinstpaid_4499208L_MedianImp',
       'numinstpaidearly3d_3546850L_MedianImp',
       'numinstpaidearly3dest_4493216L_MedianImp',
       'numinstpaidearly5d_1087L_MedianImp',
       'numinstpaidearly5dest_4493211L_MedianImp',
       'numinstpaidearly5dobd_4499205L_MedianImp',
       'numinstpaidearly_338L_MedianImp',
       'numinstpaidearlyest_4493214L_MedianImp',
       'numinstpaidlastcontr_4325080L_MedianImp',
       'numinstpaidlate1d_3546852L_MedianImp',
       'numinstregularpaid_973L_MedianImp',
       'numinstregularpaidest_4493210L_MedianImp',
       'numinsttopaygr_769L_MedianImp',
       'numinsttopaygrest_4493213L_MedianImp',
       'numinstunpaidmax_3546851L_MedianImp',
       'numinstunpaidmaxest_4493212L_MedianImp',
       'numnotactivated_1143L_MedianImp',
       'numpmtchanneldd_318L_MedianImp', 'numrejects9m_859L_MedianImp',
       'pctinstlsallpaidearl3d_427L_MedianImp',
       'pctinstlsallpaidlat10d_839L_MedianImp',
       'pctinstlsallpaidlate1d_3546856L_MedianImp',
       'pctinstlsallpaidlate4d_3546849L_MedianImp',
       'pctinstlsallpaidlate6d_3546844L_MedianImp',
       'pmtnum_254L_MedianImp', 'posfpd10lastmonth_333P_MedianImp',
       'posfpd30lastmonth_3976960P_MedianImp',
       'posfstqpd30lastmonth_3976962P_MedianImp', 'price_1097A_MedianImp',
       'sellerplacecnt_915L_MedianImp', 'sellerplacescnt_216L_MedianImp',
       'sumoutstandtotal_3546847A_MedianImp',
       'sumoutstandtotalest_4493215A_MedianImp', 'totaldebt_9A_MedianImp',
       'totalsettled_863A_MedianImp',
       'totinstallast1m_4525188A_MedianImp'], dtype=object)

In [111]:
VariablesToBeExcluded=['case_id','MONTH','WEEK_NUM','target']
for Variable in VariablesToBeExcluded:
    VariablesNumericas = VariablesNumericas[VariablesNumericas != Variable]

In [112]:
df_num=df11[VariablesNumericas]
df_num.shape

(20000, 512)

In [113]:
df_num

,actualdpdtolerance_344P_MinImp,amtinstpaidbefduel24m_4187115A_MinImp,annuity_780A_MinImp,annuitynextmonth_57A_MinImp,applicationcnt_361L_MinImp,applications30d_658L_MinImp,applicationscnt_1086L_MinImp,applicationscnt_464L_MinImp,applicationscnt_629L_MinImp,applicationscnt_867L_MinImp,...,posfpd30lastmonth_3976960P_MedianImp,posfstqpd30lastmonth_3976962P_MedianImp,price_1097A_MedianImp,sellerplacecnt_915L_MedianImp,sellerplacescnt_216L_MedianImp,sumoutstandtotal_3546847A_MedianImp,sumoutstandtotalest_4493215A_MedianImp,totaldebt_9A_MedianImp,totalsettled_863A_MedianImp,totinstallast1m_4525188A_MedianImp
0,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,24072.0,0.0,1.0,0.0,0.0,0.0,29586.000,6079.8003
1,0.0,6795.60,2477.600,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,26000.0,0.0,0.0,0.0,0.0,0.0,14531.601,6079.8003
2,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,24072.0,0.0,1.0,0.0,0.0,0.0,29586.000,6079.8003
3,0.0,214471.80,3192.200,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,35404.0,1.0,0.0,0.0,0.0,0.0,323300.000,6079.8003
4,0.0,201225.62,11481.601,5748.8003,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,24072.0,0.0,1.0,34188.6,0.0,34188.6,383542.400,6079.8003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,24072.0,0.0,1.0,0.0,0.0,0.0,29586.000,6079.8003
19996,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,24072.0,0.0,1.0,0.0,0.0,0.0,29586.000,6079.8003
19997,0.0,0.00,2158.200,0.0000,0.0,0.0,0.0,2.0,0.0,0.0,...,0.0,0.0,25898.0,0.0,0.0,0.0,0.0,0.0,0.000,6079.8003
19998,0.0,0.00,3160.800,3358.4001,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,32030.0,1.0,1.0,10191.2,0.0,10191.2,6600.000,6079.8003
19999,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,24072.0,0.0,1.0,0.0,0.0,0.0,29586.000,6079.8003

In [114]:
df_num.shape

(20000, 512)

### 5.5.2.- Categóricas

In [115]:
MaskCatNotNull=(df_fields_imputed.type=='object') & (df_fields_imputed.nulls==0)

In [116]:
VariablesCategoricas=df_fields_imputed[MaskCatNotNull].index.values
VariablesCategoricas

array(['date_decision', '_merge', 'bankacctype_710L_MostFreqImp',
       'cardtype_51L_MostFreqImp', 'credtype_322L_MostFreqImp',
       'datefirstoffer_1144D_MostFreqImp',
       'datelastinstal40dpd_247D_MostFreqImp',
       'datelastunpaid_3546854D_MostFreqImp',
       'disbursementtype_67L_MostFreqImp',
       'dtlastpmtallstes_4499206D_MostFreqImp',
       'firstclxcampaign_1125D_MostFreqImp',
       'firstdatedue_489D_MostFreqImp',
       'inittransactioncode_186L_MostFreqImp',
       'lastactivateddate_801D_MostFreqImp',
       'lastapplicationdate_877D_MostFreqImp',
       'lastapprcommoditycat_1041M_MostFreqImp',
       'lastapprcommoditytypec_5251766M_MostFreqImp',
       'lastapprdate_640D_MostFreqImp',
       'lastcancelreason_561M_MostFreqImp',
       'lastdelinqdate_224D_MostFreqImp',
       'lastrejectcommoditycat_161M_MostFreqImp',
       'lastrejectcommodtypec_5251769M_MostFreqImp',
       'lastrejectdate_50D_MostFreqImp',
       'lastrejectreason_759M_MostFreqImp',
       'lastrejectreasonclient_4145040M_MostFreqImp',
       'lastrepayingdate_696D_MostFreqImp', 'lastst_736L_MostFreqImp',
       'maxdpdinstldate_3546855D_MostFreqImp',
       'paytype1st_925L_MostFreqImp', 'paytype_783L_MostFreqImp',
       'payvacationpostpone_4187118D_MostFreqImp',
       'previouscontdistrict_112M_MostFreqImp',
       'twobodfilling_608L_MostFreqImp', 'typesuite_864L_MostFreqImp',
       'validfrom_1069D_MostFreqImp', 'bankacctype_710L_NullValImp',
       'cardtype_51L_NullValImp', 'credtype_322L_NullValImp',
       'datefirstoffer_1144D_NullValImp',
       'datelastinstal40dpd_247D_NullValImp',
       'datelastunpaid_3546854D_NullValImp',
       'disbursementtype_67L_NullValImp',
       'dtlastpmtallstes_4499206D_NullValImp',
       'equalitydataagreement_891L_NullValImp',
       'equalityempfrom_62L_NullValImp',
       'firstclxcampaign_1125D_NullValImp',
       'firstdatedue_489D_NullValImp',
       'inittransactioncode_186L_NullValImp',
       'isbidproduct_1095L_NullValImp',
       'isbidproductrequest_292L_NullValImp',
       'isdebitcard_729L_NullValImp', 'lastactivateddate_801D_NullValImp',
       'lastapplicationdate_877D_NullValImp',
       'lastapprcommoditycat_1041M_NullValImp',
       'lastapprcommoditytypec_5251766M_NullValImp',
       'lastapprdate_640D_NullValImp', 'lastcancelreason_561M_NullValImp',
       'lastdelinqdate_224D_NullValImp',
       'lastrejectcommoditycat_161M_NullValImp',
       'lastrejectcommodtypec_5251769M_NullValImp',
       'lastrejectdate_50D_NullValImp',
       'lastrejectreason_759M_NullValImp',
       'lastrejectreasonclient_4145040M_NullValImp',
       'lastrepayingdate_696D_NullValImp', 'lastst_736L_NullValImp',
       'maxdpdinstldate_3546855D_NullValImp', 'opencred_647L_NullValImp',
       'paytype1st_925L_NullValImp', 'paytype_783L_NullValImp',
       'payvacationpostpone_4187118D_NullValImp',
       'previouscontdistrict_112M_NullValImp',
       'twobodfilling_608L_NullValImp', 'typesuite_864L_NullValImp',
       'validfrom_1069D_NullValImp'], dtype=object)

In [117]:
VariablesCategoricas=[
    'typesuite_864L_NullValImp',
    'paytype_783L_NullValImp',
    'paytype1st_925L_NullValImp',
    'lastrejectcommodtypec_5251769M_NullValImp',
    'lastapprcommoditytypec_5251766M_NullValImp',
    'isdebitcard_729L_NullValImp',
    'isbidproductrequest_292L_NullValImp',
    'bankacctype_710L_NullValImp',
    'twobodfilling_608L_MostFreqImp',
    'cardtype_51L_MostFreqImp',
    'twobodfilling_608L_NullValImp',
    'opencred_647L_NullValImp',
    'isbidproduct_1095L_NullValImp',
    'equalityempfrom_62L_NullValImp',
    'equalitydataagreement_891L_NullValImp',
    'cardtype_51L_NullValImp',
    'inittransactioncode_186L_MostFreqImp',
    'disbursementtype_67L_MostFreqImp',
    'credtype_322L_MostFreqImp',
    'inittransactioncode_186L_NullValImp',
    'disbursementtype_67L_NullValImp',
    'credtype_322L_NullValImp',
    'lastst_736L_MostFreqImp',
    'lastst_736L_NullValImp'  
]

In [118]:
# Conjunto pequeño de variables categóricas (Las que tienen menos valores diferentes)
df_cat=df11[VariablesCategoricas]

In [119]:
df_cat_dum=pd.get_dummies(df_cat,drop_first=True)

In [120]:
df_cat_dum.shape

(20000, 52)

In [121]:
df_cat_dum.dtypes.value_counts()

uint8    52
dtype: int64

### 5.5.3.- Tabla minable

In [122]:
df_Xy=pd.concat([df_num,df_cat_dum,
                 df[VariableObjetivo]],axis=1)

In [123]:
df_Xy.shape

(20000, 565)

In [124]:
df_Xy

,actualdpdtolerance_344P_MinImp,amtinstpaidbefduel24m_4187115A_MinImp,annuity_780A_MinImp,annuitynextmonth_57A_MinImp,applicationcnt_361L_MinImp,applications30d_658L_MinImp,applicationscnt_1086L_MinImp,applicationscnt_464L_MinImp,applicationscnt_629L_MinImp,applicationscnt_867L_MinImp,...,lastst_736L_MostFreqImp_T,lastst_736L_NullValImp_D,lastst_736L_NullValImp_K,lastst_736L_NullValImp_L,lastst_736L_NullValImp_N,lastst_736L_NullValImp_NullValue,lastst_736L_NullValImp_Q,lastst_736L_NullValImp_S,lastst_736L_NullValImp_T,target
0,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
1,0.0,6795.60,2477.600,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,0,0,0,0,0,0
2,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
3,0.0,214471.80,3192.200,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,1
4,0.0,201225.62,11481.601,5748.8003,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19995,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
19996,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
19997,0.0,0.00,2158.200,0.0000,0.0,0.0,0.0,2.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0
19998,0.0,0.00,3160.800,3358.4001,0.0,0.0,0.0,0.0,0.0,1.0,...,0,0,0,0,0,0,0,0,0,0
19999,0.0,0.00,250.000,0.0000,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,1,0,0,0,0

In [125]:
df_Xy.to_csv('../output/'+OutputFolder+'/'+StrNow+'/df_Xy.csv')

In [126]:
df_fields_Xy=DescribeDf(df_Xy)

In [127]:
df_fields_Xy.to_csv('../output/'+OutputFolder+'/'+StrNow+'/df_fields_Xy.csv')